# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_article_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='userID',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_full_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
